//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMStyle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBFMStye : DbContext
    {
        public DBFMStye()
            : base("name=DBFMStye")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<danhmuc> danhmucs { get; set; }
        public DbSet<dat_hang> dat_hang { get; set; }
        public DbSet<dat_hang_detail> dat_hang_detail { get; set; }
        public DbSet<khuyenmai> khuyenmais { get; set; }
        public DbSet<lien_he> lien_he { get; set; }
        public DbSet<nguoidung> nguoidungs { get; set; }
        public DbSet<phuong_thuc_thanh_toan> phuong_thuc_thanh_toan { get; set; }
        public DbSet<quangcao> quangcaos { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<san_pham> san_pham { get; set; }
        public DbSet<slide> slides { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<view_lienhe> view_lienhe { get; set; }
    }
}
