#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMStyle.Areas.Admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FMStyleDB")]
	public partial class DBFMStyleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdanhmuc(danhmuc instance);
    partial void Updatedanhmuc(danhmuc instance);
    partial void Deletedanhmuc(danhmuc instance);
    partial void Insertview_lienhe(view_lienhe instance);
    partial void Updateview_lienhe(view_lienhe instance);
    partial void Deleteview_lienhe(view_lienhe instance);
    partial void Insertdat_hang(dat_hang instance);
    partial void Updatedat_hang(dat_hang instance);
    partial void Deletedat_hang(dat_hang instance);
    partial void Insertdat_hang_detail(dat_hang_detail instance);
    partial void Updatedat_hang_detail(dat_hang_detail instance);
    partial void Deletedat_hang_detail(dat_hang_detail instance);
    partial void Insertkhuyenmai(khuyenmai instance);
    partial void Updatekhuyenmai(khuyenmai instance);
    partial void Deletekhuyenmai(khuyenmai instance);
    partial void Insertlien_he(lien_he instance);
    partial void Updatelien_he(lien_he instance);
    partial void Deletelien_he(lien_he instance);
    partial void Insertnguoidung(nguoidung instance);
    partial void Updatenguoidung(nguoidung instance);
    partial void Deletenguoidung(nguoidung instance);
    partial void Insertphuong_thuc_thanh_toan(phuong_thuc_thanh_toan instance);
    partial void Updatephuong_thuc_thanh_toan(phuong_thuc_thanh_toan instance);
    partial void Deletephuong_thuc_thanh_toan(phuong_thuc_thanh_toan instance);
    partial void Insertquangcao(quangcao instance);
    partial void Updatequangcao(quangcao instance);
    partial void Deletequangcao(quangcao instance);
    partial void Insertrole(role instance);
    partial void Updaterole(role instance);
    partial void Deleterole(role instance);
    partial void Insertsan_pham(san_pham instance);
    partial void Updatesan_pham(san_pham instance);
    partial void Deletesan_pham(san_pham instance);
    partial void Insertslide(slide instance);
    partial void Updateslide(slide instance);
    partial void Deleteslide(slide instance);
    #endregion
		
		public DBFMStyleDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["fmstyledbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBFMStyleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFMStyleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFMStyleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFMStyleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<danhmuc> danhmucs
		{
			get
			{
				return this.GetTable<danhmuc>();
			}
		}
		
		public System.Data.Linq.Table<view_lienhe> view_lienhes
		{
			get
			{
				return this.GetTable<view_lienhe>();
			}
		}
		
		public System.Data.Linq.Table<dat_hang> dat_hangs
		{
			get
			{
				return this.GetTable<dat_hang>();
			}
		}
		
		public System.Data.Linq.Table<dat_hang_detail> dat_hang_details
		{
			get
			{
				return this.GetTable<dat_hang_detail>();
			}
		}
		
		public System.Data.Linq.Table<khuyenmai> khuyenmais
		{
			get
			{
				return this.GetTable<khuyenmai>();
			}
		}
		
		public System.Data.Linq.Table<lien_he> lien_hes
		{
			get
			{
				return this.GetTable<lien_he>();
			}
		}
		
		public System.Data.Linq.Table<nguoidung> nguoidungs
		{
			get
			{
				return this.GetTable<nguoidung>();
			}
		}
		
		public System.Data.Linq.Table<phuong_thuc_thanh_toan> phuong_thuc_thanh_toans
		{
			get
			{
				return this.GetTable<phuong_thuc_thanh_toan>();
			}
		}
		
		public System.Data.Linq.Table<quangcao> quangcaos
		{
			get
			{
				return this.GetTable<quangcao>();
			}
		}
		
		public System.Data.Linq.Table<role> roles
		{
			get
			{
				return this.GetTable<role>();
			}
		}
		
		public System.Data.Linq.Table<san_pham> san_phams
		{
			get
			{
				return this.GetTable<san_pham>();
			}
		}
		
		public System.Data.Linq.Table<slide> slides
		{
			get
			{
				return this.GetTable<slide>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhmuc")]
	public partial class danhmuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_danhmuc;
		
		private string _ten_danhmuc;
		
		private System.Nullable<double> _groupdanhmuc;
		
		private EntitySet<san_pham> _san_phams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danhmucChanging(int value);
    partial void Onid_danhmucChanged();
    partial void Onten_danhmucChanging(string value);
    partial void Onten_danhmucChanged();
    partial void OngroupdanhmucChanging(System.Nullable<double> value);
    partial void OngroupdanhmucChanged();
    #endregion
		
		public danhmuc()
		{
			this._san_phams = new EntitySet<san_pham>(new Action<san_pham>(this.attach_san_phams), new Action<san_pham>(this.detach_san_phams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_danhmuc
		{
			get
			{
				return this._id_danhmuc;
			}
			set
			{
				if ((this._id_danhmuc != value))
				{
					this.Onid_danhmucChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc = value;
					this.SendPropertyChanged("id_danhmuc");
					this.Onid_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danhmuc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_danhmuc
		{
			get
			{
				return this._ten_danhmuc;
			}
			set
			{
				if ((this._ten_danhmuc != value))
				{
					this.Onten_danhmucChanging(value);
					this.SendPropertyChanging();
					this._ten_danhmuc = value;
					this.SendPropertyChanged("ten_danhmuc");
					this.Onten_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupdanhmuc", DbType="Float")]
		public System.Nullable<double> groupdanhmuc
		{
			get
			{
				return this._groupdanhmuc;
			}
			set
			{
				if ((this._groupdanhmuc != value))
				{
					this.OngroupdanhmucChanging(value);
					this.SendPropertyChanging();
					this._groupdanhmuc = value;
					this.SendPropertyChanged("groupdanhmuc");
					this.OngroupdanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_san_pham", Storage="_san_phams", ThisKey="id_danhmuc", OtherKey="id_danhmuc")]
		public EntitySet<san_pham> san_phams
		{
			get
			{
				return this._san_phams;
			}
			set
			{
				this._san_phams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_san_phams(san_pham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = this;
		}
		
		private void detach_san_phams(san_pham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_lienhe")]
	public partial class view_lienhe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_view_lienhe;
		
		private System.Nullable<int> _id_lienhe;
		
		private System.Nullable<int> _id_user;
		
		private EntityRef<lien_he> _lien_he;
		
		private EntityRef<nguoidung> _nguoidung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_view_lienheChanging(int value);
    partial void Onid_view_lienheChanged();
    partial void Onid_lienheChanging(System.Nullable<int> value);
    partial void Onid_lienheChanged();
    partial void Onid_userChanging(System.Nullable<int> value);
    partial void Onid_userChanged();
    #endregion
		
		public view_lienhe()
		{
			this._lien_he = default(EntityRef<lien_he>);
			this._nguoidung = default(EntityRef<nguoidung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_view_lienhe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_view_lienhe
		{
			get
			{
				return this._id_view_lienhe;
			}
			set
			{
				if ((this._id_view_lienhe != value))
				{
					this.Onid_view_lienheChanging(value);
					this.SendPropertyChanging();
					this._id_view_lienhe = value;
					this.SendPropertyChanged("id_view_lienhe");
					this.Onid_view_lienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lienhe", DbType="Int")]
		public System.Nullable<int> id_lienhe
		{
			get
			{
				return this._id_lienhe;
			}
			set
			{
				if ((this._id_lienhe != value))
				{
					if (this._lien_he.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_lienheChanging(value);
					this.SendPropertyChanging();
					this._id_lienhe = value;
					this.SendPropertyChanged("id_lienhe");
					this.Onid_lienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int")]
		public System.Nullable<int> id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._nguoidung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lien_he_view_lienhe", Storage="_lien_he", ThisKey="id_lienhe", OtherKey="id_lienhe", IsForeignKey=true)]
		public lien_he lien_he
		{
			get
			{
				return this._lien_he.Entity;
			}
			set
			{
				lien_he previousValue = this._lien_he.Entity;
				if (((previousValue != value) 
							|| (this._lien_he.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lien_he.Entity = null;
						previousValue.view_lienhes.Remove(this);
					}
					this._lien_he.Entity = value;
					if ((value != null))
					{
						value.view_lienhes.Add(this);
						this._id_lienhe = value.id_lienhe;
					}
					else
					{
						this._id_lienhe = default(Nullable<int>);
					}
					this.SendPropertyChanged("lien_he");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_view_lienhe", Storage="_nguoidung", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true)]
		public nguoidung nguoidung
		{
			get
			{
				return this._nguoidung.Entity;
			}
			set
			{
				nguoidung previousValue = this._nguoidung.Entity;
				if (((previousValue != value) 
							|| (this._nguoidung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoidung.Entity = null;
						previousValue.view_lienhes.Remove(this);
					}
					this._nguoidung.Entity = value;
					if ((value != null))
					{
						value.view_lienhes.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoidung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dat_hang")]
	public partial class dat_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dathang;
		
		private System.Nullable<int> _id_user;
		
		private System.Nullable<int> _id_pt;
		
		private System.Nullable<bool> _trang_thai;
		
		private System.DateTime _ngaydathang;
		
		private EntitySet<dat_hang_detail> _dat_hang_details;
		
		private EntityRef<nguoidung> _nguoidung;
		
		private EntityRef<phuong_thuc_thanh_toan> _phuong_thuc_thanh_toan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dathangChanging(int value);
    partial void Onid_dathangChanged();
    partial void Onid_userChanging(System.Nullable<int> value);
    partial void Onid_userChanged();
    partial void Onid_ptChanging(System.Nullable<int> value);
    partial void Onid_ptChanged();
    partial void Ontrang_thaiChanging(System.Nullable<bool> value);
    partial void Ontrang_thaiChanged();
    partial void OnngaydathangChanging(System.DateTime value);
    partial void OnngaydathangChanged();
    #endregion
		
		public dat_hang()
		{
			this._dat_hang_details = new EntitySet<dat_hang_detail>(new Action<dat_hang_detail>(this.attach_dat_hang_details), new Action<dat_hang_detail>(this.detach_dat_hang_details));
			this._nguoidung = default(EntityRef<nguoidung>);
			this._phuong_thuc_thanh_toan = default(EntityRef<phuong_thuc_thanh_toan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dathang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dathang
		{
			get
			{
				return this._id_dathang;
			}
			set
			{
				if ((this._id_dathang != value))
				{
					this.Onid_dathangChanging(value);
					this.SendPropertyChanging();
					this._id_dathang = value;
					this.SendPropertyChanged("id_dathang");
					this.Onid_dathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int")]
		public System.Nullable<int> id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._nguoidung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pt", DbType="Int")]
		public System.Nullable<int> id_pt
		{
			get
			{
				return this._id_pt;
			}
			set
			{
				if ((this._id_pt != value))
				{
					if (this._phuong_thuc_thanh_toan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ptChanging(value);
					this.SendPropertyChanging();
					this._id_pt = value;
					this.SendPropertyChanged("id_pt");
					this.Onid_ptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="Bit")]
		public System.Nullable<bool> trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydathang", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ngaydathang
		{
			get
			{
				return this._ngaydathang;
			}
			set
			{
				if ((this._ngaydathang != value))
				{
					this.OnngaydathangChanging(value);
					this.SendPropertyChanging();
					this._ngaydathang = value;
					this.SendPropertyChanged("ngaydathang");
					this.OnngaydathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dat_hang_dat_hang_detail", Storage="_dat_hang_details", ThisKey="id_dathang", OtherKey="id_dathang")]
		public EntitySet<dat_hang_detail> dat_hang_details
		{
			get
			{
				return this._dat_hang_details;
			}
			set
			{
				this._dat_hang_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_dat_hang", Storage="_nguoidung", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true)]
		public nguoidung nguoidung
		{
			get
			{
				return this._nguoidung.Entity;
			}
			set
			{
				nguoidung previousValue = this._nguoidung.Entity;
				if (((previousValue != value) 
							|| (this._nguoidung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoidung.Entity = null;
						previousValue.dat_hangs.Remove(this);
					}
					this._nguoidung.Entity = value;
					if ((value != null))
					{
						value.dat_hangs.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoidung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phuong_thuc_thanh_toan_dat_hang", Storage="_phuong_thuc_thanh_toan", ThisKey="id_pt", OtherKey="id_pt", IsForeignKey=true)]
		public phuong_thuc_thanh_toan phuong_thuc_thanh_toan
		{
			get
			{
				return this._phuong_thuc_thanh_toan.Entity;
			}
			set
			{
				phuong_thuc_thanh_toan previousValue = this._phuong_thuc_thanh_toan.Entity;
				if (((previousValue != value) 
							|| (this._phuong_thuc_thanh_toan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phuong_thuc_thanh_toan.Entity = null;
						previousValue.dat_hangs.Remove(this);
					}
					this._phuong_thuc_thanh_toan.Entity = value;
					if ((value != null))
					{
						value.dat_hangs.Add(this);
						this._id_pt = value.id_pt;
					}
					else
					{
						this._id_pt = default(Nullable<int>);
					}
					this.SendPropertyChanged("phuong_thuc_thanh_toan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dat_hang_details(dat_hang_detail entity)
		{
			this.SendPropertyChanging();
			entity.dat_hang = this;
		}
		
		private void detach_dat_hang_details(dat_hang_detail entity)
		{
			this.SendPropertyChanging();
			entity.dat_hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dat_hang_detail")]
	public partial class dat_hang_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dathang_detail;
		
		private System.Nullable<int> _id_sanpham;
		
		private System.Nullable<int> _id_dathang;
		
		private int _soluong;
		
		private string _size;
		
		private EntityRef<dat_hang> _dat_hang;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dathang_detailChanging(int value);
    partial void Onid_dathang_detailChanged();
    partial void Onid_sanphamChanging(System.Nullable<int> value);
    partial void Onid_sanphamChanged();
    partial void Onid_dathangChanging(System.Nullable<int> value);
    partial void Onid_dathangChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OnsizeChanging(string value);
    partial void OnsizeChanged();
    #endregion
		
		public dat_hang_detail()
		{
			this._dat_hang = default(EntityRef<dat_hang>);
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dathang_detail", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dathang_detail
		{
			get
			{
				return this._id_dathang_detail;
			}
			set
			{
				if ((this._id_dathang_detail != value))
				{
					this.Onid_dathang_detailChanging(value);
					this.SendPropertyChanging();
					this._id_dathang_detail = value;
					this.SendPropertyChanged("id_dathang_detail");
					this.Onid_dathang_detailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", DbType="Int")]
		public System.Nullable<int> id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dathang", DbType="Int")]
		public System.Nullable<int> id_dathang
		{
			get
			{
				return this._id_dathang;
			}
			set
			{
				if ((this._id_dathang != value))
				{
					if (this._dat_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dathangChanging(value);
					this.SendPropertyChanging();
					this._id_dathang = value;
					this.SendPropertyChanged("id_dathang");
					this.Onid_dathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(2)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dat_hang_dat_hang_detail", Storage="_dat_hang", ThisKey="id_dathang", OtherKey="id_dathang", IsForeignKey=true)]
		public dat_hang dat_hang
		{
			get
			{
				return this._dat_hang.Entity;
			}
			set
			{
				dat_hang previousValue = this._dat_hang.Entity;
				if (((previousValue != value) 
							|| (this._dat_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dat_hang.Entity = null;
						previousValue.dat_hang_details.Remove(this);
					}
					this._dat_hang.Entity = value;
					if ((value != null))
					{
						value.dat_hang_details.Add(this);
						this._id_dathang = value.id_dathang;
					}
					else
					{
						this._id_dathang = default(Nullable<int>);
					}
					this.SendPropertyChanged("dat_hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_dat_hang_detail", Storage="_san_pham", ThisKey="id_sanpham", OtherKey="id_sanpham", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.dat_hang_details.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.dat_hang_details.Add(this);
						this._id_sanpham = value.id_sanpham;
					}
					else
					{
						this._id_sanpham = default(Nullable<int>);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khuyenmai")]
	public partial class khuyenmai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_khuyenmai;
		
		private string _ten_khuyenmai;
		
		private int _giatri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khuyenmaiChanging(int value);
    partial void Onid_khuyenmaiChanged();
    partial void Onten_khuyenmaiChanging(string value);
    partial void Onten_khuyenmaiChanged();
    partial void OngiatriChanging(int value);
    partial void OngiatriChanged();
    #endregion
		
		public khuyenmai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khuyenmai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_khuyenmai
		{
			get
			{
				return this._id_khuyenmai;
			}
			set
			{
				if ((this._id_khuyenmai != value))
				{
					this.Onid_khuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._id_khuyenmai = value;
					this.SendPropertyChanged("id_khuyenmai");
					this.Onid_khuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khuyenmai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_khuyenmai
		{
			get
			{
				return this._ten_khuyenmai;
			}
			set
			{
				if ((this._ten_khuyenmai != value))
				{
					this.Onten_khuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._ten_khuyenmai = value;
					this.SendPropertyChanged("ten_khuyenmai");
					this.Onten_khuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Int NOT NULL")]
		public int giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lien_he")]
	public partial class lien_he : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lienhe;
		
		private string _hoten;
		
		private string _email;
		
		private string _sdt;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaygui;
		
		private string _diachi;
		
		private EntitySet<view_lienhe> _view_lienhes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lienheChanging(int value);
    partial void Onid_lienheChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngayguiChanging(System.Nullable<System.DateTime> value);
    partial void OnngayguiChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public lien_he()
		{
			this._view_lienhes = new EntitySet<view_lienhe>(new Action<view_lienhe>(this.attach_view_lienhes), new Action<view_lienhe>(this.detach_view_lienhes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lienhe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_lienhe
		{
			get
			{
				return this._id_lienhe;
			}
			set
			{
				if ((this._id_lienhe != value))
				{
					this.Onid_lienheChanging(value);
					this.SendPropertyChanging();
					this._id_lienhe = value;
					this.SendPropertyChanged("id_lienhe");
					this.Onid_lienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaygui", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaygui
		{
			get
			{
				return this._ngaygui;
			}
			set
			{
				if ((this._ngaygui != value))
				{
					this.OnngayguiChanging(value);
					this.SendPropertyChanging();
					this._ngaygui = value;
					this.SendPropertyChanged("ngaygui");
					this.OnngayguiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lien_he_view_lienhe", Storage="_view_lienhes", ThisKey="id_lienhe", OtherKey="id_lienhe")]
		public EntitySet<view_lienhe> view_lienhes
		{
			get
			{
				return this._view_lienhes;
			}
			set
			{
				this._view_lienhes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_view_lienhes(view_lienhe entity)
		{
			this.SendPropertyChanging();
			entity.lien_he = this;
		}
		
		private void detach_view_lienhes(view_lienhe entity)
		{
			this.SendPropertyChanging();
			entity.lien_he = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nguoidung")]
	public partial class nguoidung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _username;
		
		private string _password;
		
		private string _hoten;
		
		private string _sdt;
		
		private string _diachi;
		
		private System.Nullable<int> _role;
		
		private string _email;
		
		private EntitySet<view_lienhe> _view_lienhes;
		
		private EntitySet<dat_hang> _dat_hangs;
		
		private EntityRef<role> _role1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnroleChanging(System.Nullable<int> value);
    partial void OnroleChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public nguoidung()
		{
			this._view_lienhes = new EntitySet<view_lienhe>(new Action<view_lienhe>(this.attach_view_lienhes), new Action<view_lienhe>(this.detach_view_lienhes));
			this._dat_hangs = new EntitySet<dat_hang>(new Action<dat_hang>(this.attach_dat_hangs), new Action<dat_hang>(this.detach_dat_hangs));
			this._role1 = default(EntityRef<role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int")]
		public System.Nullable<int> role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					if (this._role1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_view_lienhe", Storage="_view_lienhes", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<view_lienhe> view_lienhes
		{
			get
			{
				return this._view_lienhes;
			}
			set
			{
				this._view_lienhes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoidung_dat_hang", Storage="_dat_hangs", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<dat_hang> dat_hangs
		{
			get
			{
				return this._dat_hangs;
			}
			set
			{
				this._dat_hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_nguoidung", Storage="_role1", ThisKey="role", OtherKey="id_role", IsForeignKey=true)]
		public role role1
		{
			get
			{
				return this._role1.Entity;
			}
			set
			{
				role previousValue = this._role1.Entity;
				if (((previousValue != value) 
							|| (this._role1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._role1.Entity = null;
						previousValue.nguoidungs.Remove(this);
					}
					this._role1.Entity = value;
					if ((value != null))
					{
						value.nguoidungs.Add(this);
						this._role = value.id_role;
					}
					else
					{
						this._role = default(Nullable<int>);
					}
					this.SendPropertyChanged("role1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_view_lienhes(view_lienhe entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = this;
		}
		
		private void detach_view_lienhes(view_lienhe entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = null;
		}
		
		private void attach_dat_hangs(dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = this;
		}
		
		private void detach_dat_hangs(dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.nguoidung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phuong_thuc_thanh_toan")]
	public partial class phuong_thuc_thanh_toan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pt;
		
		private string _ten_phuongthuc;
		
		private string _chitiet;
		
		private EntitySet<dat_hang> _dat_hangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ptChanging(int value);
    partial void Onid_ptChanged();
    partial void Onten_phuongthucChanging(string value);
    partial void Onten_phuongthucChanged();
    partial void OnchitietChanging(string value);
    partial void OnchitietChanged();
    #endregion
		
		public phuong_thuc_thanh_toan()
		{
			this._dat_hangs = new EntitySet<dat_hang>(new Action<dat_hang>(this.attach_dat_hangs), new Action<dat_hang>(this.detach_dat_hangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pt
		{
			get
			{
				return this._id_pt;
			}
			set
			{
				if ((this._id_pt != value))
				{
					this.Onid_ptChanging(value);
					this.SendPropertyChanging();
					this._id_pt = value;
					this.SendPropertyChanged("id_pt");
					this.Onid_ptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_phuongthuc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_phuongthuc
		{
			get
			{
				return this._ten_phuongthuc;
			}
			set
			{
				if ((this._ten_phuongthuc != value))
				{
					this.Onten_phuongthucChanging(value);
					this.SendPropertyChanging();
					this._ten_phuongthuc = value;
					this.SendPropertyChanged("ten_phuongthuc");
					this.Onten_phuongthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitiet", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string chitiet
		{
			get
			{
				return this._chitiet;
			}
			set
			{
				if ((this._chitiet != value))
				{
					this.OnchitietChanging(value);
					this.SendPropertyChanging();
					this._chitiet = value;
					this.SendPropertyChanged("chitiet");
					this.OnchitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phuong_thuc_thanh_toan_dat_hang", Storage="_dat_hangs", ThisKey="id_pt", OtherKey="id_pt")]
		public EntitySet<dat_hang> dat_hangs
		{
			get
			{
				return this._dat_hangs;
			}
			set
			{
				this._dat_hangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dat_hangs(dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.phuong_thuc_thanh_toan = this;
		}
		
		private void detach_dat_hangs(dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.phuong_thuc_thanh_toan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quangcao")]
	public partial class quangcao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_adv;
		
		private string _ten;
		
		private string _link;
		
		private string _hinhanh;
		
		private System.Nullable<bool> _trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_advChanging(int value);
    partial void Onid_advChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public quangcao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_adv
		{
			get
			{
				return this._id_adv;
			}
			set
			{
				if ((this._id_adv != value))
				{
					this.Onid_advChanging(value);
					this.SendPropertyChanging();
					this._id_adv = value;
					this.SendPropertyChanged("id_adv");
					this.Onid_advChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(200)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.role")]
	public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_role;
		
		private string _role1;
		
		private System.Nullable<bool> _truycap_cms;
		
		private System.Nullable<bool> _special;
		
		private EntitySet<nguoidung> _nguoidungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_roleChanging(int value);
    partial void Onid_roleChanged();
    partial void Onrole1Changing(string value);
    partial void Onrole1Changed();
    partial void Ontruycap_cmsChanging(System.Nullable<bool> value);
    partial void Ontruycap_cmsChanged();
    partial void OnspecialChanging(System.Nullable<bool> value);
    partial void OnspecialChanged();
    #endregion
		
		public role()
		{
			this._nguoidungs = new EntitySet<nguoidung>(new Action<nguoidung>(this.attach_nguoidungs), new Action<nguoidung>(this.detach_nguoidungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_role", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_role
		{
			get
			{
				return this._id_role;
			}
			set
			{
				if ((this._id_role != value))
				{
					this.Onid_roleChanging(value);
					this.SendPropertyChanging();
					this._id_role = value;
					this.SendPropertyChanged("id_role");
					this.Onid_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="role", Storage="_role1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string role1
		{
			get
			{
				return this._role1;
			}
			set
			{
				if ((this._role1 != value))
				{
					this.Onrole1Changing(value);
					this.SendPropertyChanging();
					this._role1 = value;
					this.SendPropertyChanged("role1");
					this.Onrole1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_truycap_cms", DbType="Bit")]
		public System.Nullable<bool> truycap_cms
		{
			get
			{
				return this._truycap_cms;
			}
			set
			{
				if ((this._truycap_cms != value))
				{
					this.Ontruycap_cmsChanging(value);
					this.SendPropertyChanging();
					this._truycap_cms = value;
					this.SendPropertyChanged("truycap_cms");
					this.Ontruycap_cmsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special", DbType="Bit")]
		public System.Nullable<bool> special
		{
			get
			{
				return this._special;
			}
			set
			{
				if ((this._special != value))
				{
					this.OnspecialChanging(value);
					this.SendPropertyChanging();
					this._special = value;
					this.SendPropertyChanged("special");
					this.OnspecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="role_nguoidung", Storage="_nguoidungs", ThisKey="id_role", OtherKey="role")]
		public EntitySet<nguoidung> nguoidungs
		{
			get
			{
				return this._nguoidungs;
			}
			set
			{
				this._nguoidungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nguoidungs(nguoidung entity)
		{
			this.SendPropertyChanging();
			entity.role1 = this;
		}
		
		private void detach_nguoidungs(nguoidung entity)
		{
			this.SendPropertyChanging();
			entity.role1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.san_pham")]
	public partial class san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sanpham;
		
		private string _ten_sanpham;
		
		private int _soluong;
		
		private string _hinhanh;
		
		private System.Nullable<int> _id_danhmuc;
		
		private string _tt_chitiet;
		
		private System.DateTime _ngaydang;
		
		private decimal _gia;
		
		private System.Nullable<bool> _khuyenmai;
		
		private EntitySet<dat_hang_detail> _dat_hang_details;
		
		private EntityRef<danhmuc> _danhmuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sanphamChanging(int value);
    partial void Onid_sanphamChanged();
    partial void Onten_sanphamChanging(string value);
    partial void Onten_sanphamChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void Onid_danhmucChanging(System.Nullable<int> value);
    partial void Onid_danhmucChanged();
    partial void Ontt_chitietChanging(string value);
    partial void Ontt_chitietChanged();
    partial void OnngaydangChanging(System.DateTime value);
    partial void OnngaydangChanged();
    partial void OngiaChanging(decimal value);
    partial void OngiaChanged();
    partial void OnkhuyenmaiChanging(System.Nullable<bool> value);
    partial void OnkhuyenmaiChanged();
    #endregion
		
		public san_pham()
		{
			this._dat_hang_details = new EntitySet<dat_hang_detail>(new Action<dat_hang_detail>(this.attach_dat_hang_details), new Action<dat_hang_detail>(this.detach_dat_hang_details));
			this._danhmuc = default(EntityRef<danhmuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sanpham", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_sanpham
		{
			get
			{
				return this._ten_sanpham;
			}
			set
			{
				if ((this._ten_sanpham != value))
				{
					this.Onten_sanphamChanging(value);
					this.SendPropertyChanging();
					this._ten_sanpham = value;
					this.SendPropertyChanged("ten_sanpham");
					this.Onten_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(50)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc", DbType="Int")]
		public System.Nullable<int> id_danhmuc
		{
			get
			{
				return this._id_danhmuc;
			}
			set
			{
				if ((this._id_danhmuc != value))
				{
					if (this._danhmuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_danhmucChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc = value;
					this.SendPropertyChanged("id_danhmuc");
					this.Onid_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_chitiet", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string tt_chitiet
		{
			get
			{
				return this._tt_chitiet;
			}
			set
			{
				if ((this._tt_chitiet != value))
				{
					this.Ontt_chitietChanging(value);
					this.SendPropertyChanging();
					this._tt_chitiet = value;
					this.SendPropertyChanged("tt_chitiet");
					this.Ontt_chitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(18,0) NOT NULL")]
		public decimal gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenmai", DbType="Bit")]
		public System.Nullable<bool> khuyenmai
		{
			get
			{
				return this._khuyenmai;
			}
			set
			{
				if ((this._khuyenmai != value))
				{
					this.OnkhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenmai = value;
					this.SendPropertyChanged("khuyenmai");
					this.OnkhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_dat_hang_detail", Storage="_dat_hang_details", ThisKey="id_sanpham", OtherKey="id_sanpham")]
		public EntitySet<dat_hang_detail> dat_hang_details
		{
			get
			{
				return this._dat_hang_details;
			}
			set
			{
				this._dat_hang_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_san_pham", Storage="_danhmuc", ThisKey="id_danhmuc", OtherKey="id_danhmuc", IsForeignKey=true)]
		public danhmuc danhmuc
		{
			get
			{
				return this._danhmuc.Entity;
			}
			set
			{
				danhmuc previousValue = this._danhmuc.Entity;
				if (((previousValue != value) 
							|| (this._danhmuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._danhmuc.Entity = null;
						previousValue.san_phams.Remove(this);
					}
					this._danhmuc.Entity = value;
					if ((value != null))
					{
						value.san_phams.Add(this);
						this._id_danhmuc = value.id_danhmuc;
					}
					else
					{
						this._id_danhmuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("danhmuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dat_hang_details(dat_hang_detail entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_dat_hang_details(dat_hang_detail entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.slide")]
	public partial class slide : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_slide;
		
		private string _hinhanh;
		
		private string _link;
		
		private System.Nullable<int> _vitri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_slideChanging(int value);
    partial void Onid_slideChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnvitriChanging(System.Nullable<int> value);
    partial void OnvitriChanged();
    #endregion
		
		public slide()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_slide", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_slide
		{
			get
			{
				return this._id_slide;
			}
			set
			{
				if ((this._id_slide != value))
				{
					this.Onid_slideChanging(value);
					this.SendPropertyChanging();
					this._id_slide = value;
					this.SendPropertyChanged("id_slide");
					this.Onid_slideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitri", DbType="Int")]
		public System.Nullable<int> vitri
		{
			get
			{
				return this._vitri;
			}
			set
			{
				if ((this._vitri != value))
				{
					this.OnvitriChanging(value);
					this.SendPropertyChanging();
					this._vitri = value;
					this.SendPropertyChanged("vitri");
					this.OnvitriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
